name: Project Build

on:
  push:
    branches:
      - master

jobs: 
  build-python:
    name: Build and Run python project  
    runs-on: ubuntu-latest
    steps:
      - name: Check Python version
        run: python --version
      - uses: actions/checkout@v3
        name: Checkout code from GitHub
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk xvfb
          python -m pip install --upgrade pip
          pip install tk
      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Set DISPLAY variable
        run: export DISPLAY=:99
      - name: Execute Python script
        run: python main.py