name: Project Build

on:
  push:
    branches:
      - master

jobs: 
  build-python:
    name: Build and Run python project  
    runs-on: ubuntu-latest
    steps:
      - name: Check Python version
        run: python --version
      - uses: actions/checkout@v3
        name: Checkout code from GitHub
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
