name: Project Build

on:
  push:
    branches:
      - master

jobs: 
  build-python:
    name: Build and Run python project  
    runs-on: ubuntu-latest
    steps:
      - name: Check Python version
        run: python --version
      - uses: actions/checkout@v3
        name: Checkout code from GitHub
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Install pipreqs
        run: |
          python -m pip install --upgrade pip
          pip install pipreqs

      - name: Generate requirements.txt
        run: pipreqs --force .

      - name: Compare requirements.txt files
        run: |
          if ! diff requirements.txt requirements.txt.orig; then
            echo "requirements.txt is not up-to-date. Please update it with all necessary dependencies."
            exit 1
          fi
        continue-on-error: true

      - name: Display diff if exists
        if: failure()
        run: diff requirements.txt requirements.txt.orig || true
