name: Project Build

on:
  push:
    branches:
      - master

jobs: 
  test-python:
    name: Build, Test, and Run Python Project
    runs-on: ubuntu-latest
    env:
      TOTAL_MEMORY: ${{ 16000 }}  
    
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests with memory monitoring
        run: |
          python -m unittest discover -s . -p "test_*.py"